.TH MONITOR.SH 1 "October 2023" "Version 1.0"
.SH NAME
monitor.sh \- Monitor changes in a backup directory
.SH SYNOPSIS
.B monitor.sh
.SH DESCRIPTION
.B monitor.sh
is a Bash script that monitors changes in a specified backup directory. It checks for the creation, modification, and deletion of files in the directory and provides a summary of these changes.
.SH OPTIONS
None
.SH AUTHOR
This script was created by Mangaliso Linda (S2110978).
.SH REPORTING BUGS
Report any bugs to m.dlamini@alustudent.com.
.SH COPYRIGHT
This script is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.SH DISCLAIMER
This script is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

